### ISSUE TITLE
forager.yml config file

### ISSUE THREAD

**Issue by andykais** [andykais/forager-web#1]
create a config file (and argument parsing for `--config <forager_config>`) that will pass args to `Forager` constructor

**Comment by andykais** [comment]
sample:
```yml
database: '~/.local/share/forager/sqlite.db'

export_actions:
  - name: "Start FFMPEG Templates Project"
    source: './export_actions.js'
    method: 'export_media_file_to_ffmpeg_template'

custom_state:
  - name: 'Likes'
    icon: '~/.config/forager-web/custom-state-icons/heart.png'
    type: 'number'
```
